namespace: "artem_shestakov"
name: "k8s"
version: "0.1.0"
readme: "README.md"
authors:
    - "Artem Shestakov <artem.s.shestakov@gmail.com>"
# dependencies:
#     "other_namespace.collection1": ">=1.0.0"
#     "other_namespace.collection2": ">=2.0.0,<3.0.0"
#     "anderson55.my_collection": "*"    # note: "*" selects the highest version available
# license:
#     - "MIT"
# tags:
#     - demo
#     - collection
repository: "https://github.com/artem-shestakov/ansible-k8s.git"