---
- name: Kubeadm | Get kubectl stable release version
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: true
  register: kubectl_release

- name: Kubeadm | Download kubectl {{ kubectl_release.content }}
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ kubectl_release.content }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubctl
    mode: '0775'
