---
- name: Kubeadm | Install with package manager
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yaml"
  when: 
    - use_package_mgr is defined
    - use_package_mgr

- name: Kubeadm | Bootstrap cluster with Kubeadm
  ansible.builtin.include_tasks: bootstrap.yaml

- name: Join | Join nodes
  ansible.builtin.include_tasks: join.yaml
  tags: join