---
- name: Pre install | Setup for container runtimes
  ansible.builtin.import_tasks: container_runtimes.yaml

- name: Pre install | Disable SWAP
  ansible.builtin.import_tasks: swap.yaml

- name: Pre install | Check 6443 port
  ansible.builtin.wait_for:
    host: "{{ advertise_addr }}"
    port: 6443
    timeout: 5
    state: stopped
    msg: Port 6443 already in use
