---
- name: Calico | Install the Tigera Calico operator and custom resource definitions
  ansible.builtin.shell:
    cmd: >-
      KUBECONFIG=/etc/kubernetes/admin.conf
      kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/tigera-operator.yaml
  register: tigera_operator
  when: groups['control_planes'][0] == inventory_hostname
  failed_when: tigera_operator.rc != 0
  tags: calico

- name: Calico | Install Calico by creating the necessary custom resource
  ansible.builtin.shell:
    cmd: >-
      KUBECONFIG=/etc/kubernetes/admin.conf
      kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/custom-resources.yaml
  register: custom_resources
  when: groups['control_planes'][0] == inventory_hostname
  failed_when: custom_resources.rc != 0
  tags: calico
