- name: Containerd | Restart containerd
  ansible.builtin.systemd_service:
    name: containerd
    daemon_reload: true
    enabled: true
    state: restarted
  become: true
  listen: restart_containerd
