---
- name: Containerd | Download containerd archive
  ansible.builtin.get_url:
    url: https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-{{ containerd_arch }}.tar.gz
    dest: /tmp/containerd-{{ containerd_version }}-linux-{{ containerd_arch }}.tar.gz
    mode: '0440'

- name: Containerd | Unpack containerd archive
  ansible.builtin.unarchive:
    src: /tmp/containerd-{{ containerd_version }}-linux-{{ containerd_arch }}.tar.gz
    dest: "{{ containerd_bin_dir }}"
    mode: '0755'
    remote_src: true
  become: true

- name: Containerd | Create systemd service
  ansible.builtin.template:
    src: containerd.service.j2
    dest: /etc/systemd/system/containerd.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Containerd | Check if /etc/containerd exists
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Containerd | Create config.toml
  ansible.builtin.template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0640'
  notify: restart_containerd

- name: Containerd | Make sure a service unit is running
  ansible.builtin.systemd_service:
    name: containerd
    daemon_reload: true
    enabled: true
    state: started
  become: true

- name: Runc | Install runc
  ansible.builtin.import_tasks: runc.yaml

- name: Flush handlers
  meta: flush_handlers