---
- name: Runc | Get latest release version
  ansible.builtin.uri:                                                               
    url: https://api.github.com/repos/opencontainers/runc/releases/latest
    return_content: true
    body_format: json                                           
  register: json_response
  when: runc_version is not defined
  run_once: true

- name: Runc | Install runc
  ansible.builtin.get_url:                                                           
    url: "https://github.com/opencontainers/runc/releases/download/{{ json_response.json.tag_name if runc_version is not defined else runc_version }}/runc.amd64"                       
    dest: /usr/local/bin/runc
    owner: root
    group: root
    mode: '0755'
